-- Databricks notebook source
-- MAGIC %md
-- MAGIC #### Load Bronze data into dfl.nfl workspace
-- MAGIC ##### SOURCE:
-- MAGIC ##### abfss://root@sadfldatabricks.dfs.core.windows.net/raw/nfl/

-- COMMAND ----------

CREATE STREAMING LIVE TABLE bronze_pbp(
    CONSTRAINT correct_schema EXPECT (_rescued_data IS NULL)
)
COMMENT "raw weekly data from parquet export of AFC and NFC teams"
AS SELECT current_timestamp() processing_time, * FROM
    cloud_files('${source}/pbp/', 'parquet',
                 map('header', 'true', 
                     'inferSchema', 'true', 
                     'cloudFiles.inferColumnTypes', 'true'))

-- COMMAND ----------

CREATE OR REFRESH MATERIALIZED VIEW fact_play_vw (
    play_id COMMENT 'Unique identifier for the play',
    game_id COMMENT 'Unique identifier for the game',
    old_game_id COMMENT 'Old identifier for the game',
    yards_gained COMMENT 'Yards gained on the play',
    air_yards COMMENT 'Air yards on the play',
    yards_after_catch COMMENT 'Yards after the catch',
    ep COMMENT 'Expected points',
    epa COMMENT 'Expected points added',
    passing_yards COMMENT 'Passing yards',
    receiving_yards COMMENT 'Receiving yards',
    rushing_yards COMMENT 'Rushing yards',
    penalty_yards COMMENT 'Penalty yards',
    drive_play_count COMMENT 'Number of plays in the drive',
    drive_time_of_possession COMMENT 'Time of possession for the drive',
    drive_first_downs COMMENT 'Number of first downs in the drive',
    drive_yards_penalized COMMENT 'Yards penalized in the drive',
    CONSTRAINT fact_play_pk PRIMARY KEY (play_id)
)
)
COMMENT "Incremental Update of Fact Offensive Data from Play-By-Play data"
AS
SELECT
pbp.play_id,
pbp.game_id,
pbp.old_game_id,
pbp.yards_gained,
pbp.air_yards,
pbp.yards_after_catch,
pbp.ep,
pbp.epa,
pbp.passing_yards,
pbp.receiving_yards,
pbp.rushing_yards,
pbp.penalty_yards,
pbp.drive_play_count,
pbp.drive_time_of_possession,
pbp.drive_first_downs,
pbp.drive_yards_penalized
FROM STREAM(live.bronze_pbp) pbp

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### Filter the bronze data to only offensive plays and limit the fields from bronze table to only relevant ones
-- MAGIC

-- COMMAND ----------

-- Create the table
CREATE LIVE TABLE silver_pbp(
CONSTRAINT user_valid_id EXPECT (play_id IS NOT NULL) ON VIOLATION DROP ROW,
CONSTRAINT user_valid_game_id EXPECT (game_id IS NOT NULL) ON VIOLATION DROP ROW,
CONSTRAINT user_valid_old_game_id EXPECT (old_game_id IS NOT NULL) ON VIOLATION DROP ROW,
CONSTRAINT `shotgun should not be negative`    EXPECT (shotgun >= 0) ON VIOLATION DROP ROW
)
COMMENT "Incremental Update of Offensive Data from Play-By-Play data"
AS
select
--keys
pbp.play_id NOT NULL,
pbp.game_id NOT NULL,
pbp.old_game_id NOT NULL,-- (use this instead of game_id since it should be int not string)
pbp.week,
--info about game
pbp.start_time,
pbp.time_of_day,
pbp.stadium,
pbp.weather,
pbp.roof,
pbp.surface,
pbp.stadium_id,
pbp.game_stadium,
pbp.game_date,
pbp.game_half,

--info about play
pbp.qtr,
pbp.down,
pbp.goal_to_go,
pbp.time,
pbp.ydstogo,
pbp.ydsnet,
pbp.desc,
pbp.play_type,
pbp.pass,
pbp.rush,
pbp.shotgun,
pbp.no_huddle,
pbp.qb_dropback,
pbp.qb_kneel,
pbp.qb_spike,
pbp.qb_scramble,
pbp.pass_length,
pbp.pass_location,
pbp.run_location,
pbp.run_gap,
pbp.timeout,
pbp.first_down_rush,
pbp.first_down_pass,
pbp.first_down_penalty,
pbp.third_down_converted,
pbp.third_down_failed,
pbp.fourth_down_converted,
pbp.fourth_down_failed,
pbp.incomplete_pass,
pbp.interception,
pbp.safety,
pbp.penalty,
pbp.tackled_for_loss,
pbp.fumble_lost,
pbp.rush_attempt,
pbp.pass_attempt,
pbp.sack,
pbp.touchdown,
pbp.pass_touchdown,
pbp.rush_touchdown,
pbp.fumble,
pbp.complete_pass,
pbp.penalty_type,
pbp.series,
pbp.series_success,
pbp.series_result,
pbp.order_sequence,
pbp.play_clock,
pbp.play_deleted,
pbp.fixed_drive,
pbp.fixed_drive_result,
pbp.drive_inside20,
pbp.drive_ended_with_score,
pbp.drive_start_transition,
pbp.drive_end_transition,
pbp.drive_game_clock_start,
pbp.drive_game_clock_end,
pbp.drive_play_id_started,
pbp.drive_play_id_ended,
pbp.away_score,
pbp.home_score,
pbp.location,
pbp.home_coach,
pbp.away_coach,
pbp.offense_formation,
pbp.offense_personnel,
pbp.defenders_in_box,
pbp.defense_personnel,
pbp.number_of_pass_rushers,
--info about players
pbp.passer_player_id,
pbp.passer_player_name,
pbp.receiver_player_id,
pbp.receiver_player_name,
pbp.rusher_player_id,
pbp.rusher_player_name,
pbp.penalty_player_id,
--info about teams
pbp.posteam, --need to get team from pbp as the dimension tables only have current team info if they were traded mid season which is rare but happens (Bradley Chubb 2022)
pbp.posteam_type,
--postteam.team_name,
--posteam.team_conf,
--posteam.team_dvision,
--posteam.team_logo_wikipedia,
--posteam.team_logo_squared,
--defteam.team_name,
--defteam.team_conf,
--defteam.team_dvision,
--defteam.team_logo_wikipedia,
--defteam.team_logo_squared,
pbp.yardline_100,
--facts
pbp.yards_gained,
pbp.air_yards,
pbp.yards_after_catch,
pbp.ep,
pbp.epa,
pbp.passing_yards,
pbp.receiving_yards,
pbp.rushing_yards,
pbp.penalty_yards,
pbp.drive_play_count,
pbp.drive_time_of_possession,
pbp.drive_first_downs,
pbp.drive_yards_penalized
FROM STREAM(live.bronze_pbp) pbp



-- COMMAND ----------



-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### CREATE PLAY DIMENSION

-- COMMAND ----------

CREATE OR REPLACE MATERIALIZED VIEW dim_play_vw(
    play_id COMMENT 'Unique identifier for the play',
    qtr COMMENT 'Quarter of the game',
    down COMMENT 'Down number',
    goal_to_go COMMENT 'Goal to go status',
    time COMMENT 'Time of the play',
    ydstogo COMMENT 'Yards to go for a first down',
    ydsnet COMMENT 'Net yards gained',
    play_desc COMMENT 'Description of the play',
    play_type COMMENT 'Type of the play',
    pass COMMENT 'Pass play indicator',
    rush COMMENT 'Rush play indicator',
    shotgun COMMENT 'Shotgun formation indicator',
    no_huddle COMMENT 'No huddle indicator',
    qb_dropback COMMENT 'Quarterback dropback indicator',
    qb_kneel COMMENT 'Quarterback kneel indicator',
    qb_spike COMMENT 'Quarterback spike indicator',
    qb_scramble COMMENT 'Quarterback scramble indicator',
    pass_length COMMENT 'Length of the pass',
    pass_location COMMENT 'Location of the pass',
    run_location COMMENT 'Location of the run',
    run_gap COMMENT 'Gap for the run',
    timeout COMMENT 'Timeout indicator',
    first_down_rush COMMENT 'First down by rush indicator',
    first_down_pass COMMENT 'First down by pass indicator',
    first_down_penalty COMMENT 'First down by penalty indicator',
    third_down_converted COMMENT 'Third down conversion indicator',
    third_down_failed COMMENT 'Third down failure indicator',
    fourth_down_converted COMMENT 'Fourth down conversion indicator',
    fourth_down_failed COMMENT 'Fourth down failure indicator',
    incomplete_pass COMMENT 'Incomplete pass indicator',
    interception COMMENT 'Interception indicator',
    safety COMMENT 'Safety indicator',
    penalty COMMENT 'Penalty indicator',
    tackled_for_loss COMMENT 'Tackled for loss indicator',
    fumble_lost COMMENT 'Fumble lost indicator',
    rush_attempt COMMENT 'Rush attempt indicator',
    pass_attempt COMMENT 'Pass attempt indicator',
    sack COMMENT 'Sack indicator',
    touchdown COMMENT 'Touchdown indicator',
    pass_touchdown COMMENT 'Pass touchdown indicator',
    rush_touchdown COMMENT 'Rush touchdown indicator',
    fumble COMMENT 'Fumble indicator',
    complete_pass COMMENT 'Complete pass indicator',
    penalty_type COMMENT 'Type of penalty',
    series COMMENT 'Series of the play',
    series_success COMMENT 'Series success indicator',
    series_result COMMENT 'Result of the series',
    order_sequence COMMENT 'Order sequence of the play',
    play_clock COMMENT 'Play clock time',
    play_deleted COMMENT 'Play deleted indicator',
    fixed_drive COMMENT 'Fixed drive indicator',
    fixed_drive_result COMMENT 'Result of the fixed drive',
    drive_inside20 COMMENT 'Drive inside 20-yard line indicator',
    drive_ended_with_score COMMENT 'Drive ended with score indicator',
    drive_start_transition COMMENT 'Drive start transition indicator',
    drive_end_transition COMMENT 'Drive end transition indicator',
    drive_game_clock_start COMMENT 'Drive game clock start time',
    drive_game_clock_end COMMENT 'Drive game clock end time',
    CONSTRAINT dim_play_vw_pk PRIMARY KEY (play_id)
)
COMMENT 'Materialized view of play-by-play data looking at play dimension'

AS 

SELECT DISTINCT
    play_id,
    qtr,
    down,
    goal_to_go,
    time,
    ydstogo,
    ydsnet,
    desc as play_desc,
    play_type,
    pass,
    rush,
    shotgun,
    no_huddle,
    qb_dropback,
    qb_kneel,
    qb_spike,
    qb_scramble,
    pass_length,
    pass_location,
    run_location,
    run_gap,
    timeout,
    first_down_rush,
    first_down_pass,
    first_down_penalty,
    third_down_converted,
    third_down_failed,
    fourth_down_converted,
    fourth_down_failed,
    incomplete_pass,
    interception,
    safety,
    penalty,
    tackled_for_loss,
    fumble_lost,
    rush_attempt,
    pass_attempt,
    sack,
    touchdown,
    pass_touchdown,
    rush_touchdown,
    fumble,
    complete_pass,
    penalty_type,
    series,
    series_success,
    series_result,
    order_sequence,
    play_clock,
    play_deleted,
    fixed_drive,
    fixed_drive_result,
    drive_inside20,
    drive_ended_with_score,
    drive_start_transition,
    drive_end_transition,
    drive_game_clock_start,
    drive_game_clock_end,
    drive_play_id_started,
    drive_play_id_ended
FROM live.silver_pbp;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### CREATE GAME DIMENSION 

-- COMMAND ----------

CREATE OR REPLACE MATERIALIZED VIEW dim_game_vw(
    game_id  COMMENT 'Unique identifier for the game',
    old_game_id COMMENT 'Old identifier for the game',
    week COMMENT 'Week of the season',
    start_time COMMENT 'Start time of the game',
    time_of_day COMMENT 'Time of day when the game is played',
    stadium COMMENT 'Stadium where the game is played',
    weather COMMENT 'Weather conditions during the game',
    roof COMMENT 'Type of roof at the stadium',
    surface COMMENT 'Type of playing surface',
    stadium_id COMMENT 'Unique identifier for the stadium',
    game_stadium COMMENT 'Name of the game stadium',
    game_date COMMENT 'Date of the game',
    game_half COMMENT 'Half of the game',
    CONSTRAINT dim_game_vw_pk PRIMARY KEY (game_id)
)
COMMENT 'Materialized view of play by play data looking at game dimension'
AS
SELECT DISTINCT
    game_id,
    old_game_id,
    week,
    start_time,
    time_of_day,
    stadium,
    weather,
    roof,
    surface,
    stadium_id,
    game_stadium,
    game_date,
    game_half
FROM live.silver_pbp;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC #### CREATE FACT TABLE FOR PLAYS

-- COMMAND ----------

CREATE MATERIALIZED VIEW IF NOT EXISTS fact_play_vw (
    play_id COMMENT 'Unique identifier for the play',
    game_id COMMENT 'Unique identifier for the game',
    old_game_id COMMENT 'Old identifier for the game',
    week COMMENT 'Week of the season',
    qtr COMMENT 'Quarter of the game',
    down COMMENT 'Down number',
    goal_to_go COMMENT 'Goal to go status',
    time COMMENT 'Time of the play',
    ydstogo COMMENT 'Yards to go for a first down',
    ydsnet COMMENT 'Net yards gained',
    shotgun COMMENT 'Shotgun formation indicator',
    no_huddle COMMENT 'No huddle indicator',
    qb_dropback COMMENT 'Quarterback dropback indicator',
    qb_kneel COMMENT 'Quarterback kneel indicator',
    qb_spike COMMENT 'Quarterback spike indicator',
    qb_scramble COMMENT 'Quarterback scramble indicator',
    pass_length COMMENT 'Length of the pass',
    pass_location COMMENT 'Location of the pass',
    run_location COMMENT 'Location of the run',
    run_gap COMMENT 'Gap for the run',
    timeout COMMENT 'Timeout indicator',
    first_down_rush COMMENT 'First down by rush indicator',
    first_down_pass COMMENT 'First down by pass indicator',
    first_down_penalty COMMENT 'First down by penalty indicator',
    third_down_converted COMMENT 'Third down conversion indicator',
    third_down_failed COMMENT 'Third down failure indicator',
    fourth_down_converted COMMENT 'Fourth down conversion indicator',
    fourth_down_failed COMMENT 'Fourth down failure indicator',
    incomplete_pass COMMENT 'Incomplete pass indicator',
    interception COMMENT 'Interception indicator',
    safety COMMENT 'Safety indicator',
    penalty COMMENT 'Penalty indicator',
    tackled_for_loss COMMENT 'Tackled for loss indicator',
    fumble_lost COMMENT 'Fumble lost indicator',
    rush_attempt COMMENT 'Rush attempt indicator',
    pass_attempt COMMENT 'Pass attempt indicator',
    sack COMMENT 'Sack indicator',
    touchdown COMMENT 'Touchdown indicator',
    pass_touchdown COMMENT 'Pass touchdown indicator',
    rush_touchdown COMMENT 'Rush touchdown indicator',
    fumble COMMENT 'Fumble indicator',
    complete_pass COMMENT 'Complete pass indicator',
    penalty_type COMMENT 'Type of penalty',
    series COMMENT 'Series of the play',
    series_success COMMENT 'Series success indicator',
    series_result COMMENT 'Result of the series',
    order_sequence COMMENT 'Order sequence of the play',
    play_clock COMMENT 'Play clock time',
    play_deleted COMMENT 'Play deleted indicator',
    fixed_drive COMMENT 'Fixed drive indicator',
    fixed_drive_result COMMENT 'Result of the fixed drive',
    drive_inside20 COMMENT 'Drive inside 20-yard line indicator',
    drive_ended_with_score COMMENT 'Drive ended with score indicator',
    drive_start_transition COMMENT 'Drive start transition indicator',
    drive_end_transition COMMENT 'Drive end transition indicator',
    drive_game_clock_start COMMENT 'Drive game clock start time',
    drive_game_clock_end COMMENT 'Drive game clock end time',
    drive_play_id_started COMMENT 'Play ID that started the drive',
    drive_play_id_ended COMMENT 'Play ID that ended the drive',
    away_score COMMENT 'Score of the away team',
    home_score COMMENT 'Score of the home team',
    location COMMENT 'Location of the game',
    home_coach COMMENT 'Home team coach',
    away_coach COMMENT 'Away team coach',
    offense_formation COMMENT 'Offensive formation',
    offense_personnel COMMENT 'Offensive personnel',
    defenders_in_box COMMENT 'Number of defenders in the box',
    defense_personnel COMMENT 'Defensive personnel',
    number_of_pass_rushers COMMENT 'Number of pass rushers',
    passer_player_id COMMENT 'ID of the passer player',
    receiver_player_id COMMENT 'ID of the receiver player',
    rusher_player_id COMMENT 'ID of the rusher player',
    penalty_player_id COMMENT 'ID of the player who committed the penalty',
    posteam COMMENT 'Possessing team',
    posteam_type COMMENT 'Type of possessing team',
    yardline_100 COMMENT 'Yardline from the end zone',
    yards_gained COMMENT 'Yards gained on the play',
    air_yards COMMENT 'Air yards on the play',
    yards_after_catch COMMENT 'Yards after the catch',
    ep COMMENT 'Expected points',
    epa COMMENT 'Expected points added',
    passing_yards COMMENT 'Passing yards',
    receiving_yards COMMENT 'Receiving yards',
    rushing_yards COMMENT 'Rushing yards',
    penalty_yards COMMENT 'Penalty yards',
    drive_play_count COMMENT 'Number of plays in the drive',
    drive_time_of_possession COMMENT 'Time of possession for the drive',
    drive_first_downs COMMENT 'Number of first downs in the drive',
    drive_yards_penalized COMMENT 'Yards penalized in the drive',
    CONSTRAINT fact_play_pk PRIMARY KEY (play_id)
)
COMMENT "Incremental Update of Fact Offensive Data from Play-By-Play data"
AS
SELECT
    pbp.play_id,
    pbp.game_id,
    pbp.old_game_id,
    pbp.week,
    pbp.qtr,
    pbp.down,
    pbp.goal_to_go,
    pbp.time,
    pbp.ydstogo,
    pbp.ydsnet,
    pbp.shotgun,
    pbp.no_huddle,
    pbp.qb_dropback,
    pbp.qb_kneel,
    pbp.qb_spike,
    pbp.qb_scramble,
    pbp.pass_length,
    pbp.pass_location,
    pbp.run_location,
    pbp.run_gap,
    pbp.timeout,
    pbp.first_down_rush,
    pbp.first_down_pass,
    pbp.first_down_penalty,
    pbp.third_down_converted,
    pbp.third_down_failed,
    pbp.fourth_down_converted,
    pbp.fourth_down_failed,
    pbp.incomplete_pass,
    pbp.interception,
    pbp.safety,
    pbp.penalty,
    pbp.tackled_for_loss,
    pbp.fumble_lost,
    pbp.rush_attempt,
    pbp.pass_attempt,
    pbp.sack,
    pbp.touchdown,
    pbp.pass_touchdown,
    pbp.rush_touchdown,
    pbp.fumble,
    pbp.complete_pass,
    pbp.penalty_type,
    pbp.series,
    pbp.series_success,
    pbp.series_result,
    pbp.order_sequence,
    pbp.play_clock,
    pbp.play_deleted,
    pbp.fixed_drive,
    pbp.fixed_drive_result,
    pbp.drive_inside20,
    pbp.drive_ended_with_score,
    pbp.drive_start_transition,
    pbp.drive_end_transition,
    pbp.drive_game_clock_start,
    pbp.drive_game_clock_end,
    pbp.drive_play_id_started,
    pbp.drive_play_id_ended,
    pbp.away_score,
    pbp.home_score,
    pbp.location,
    pbp.home_coach,
    pbp.away_coach,
    pbp.offense_formation,
    pbp.offense_personnel,
    pbp.defenders_in_box,
    pbp.defense_personnel,
    pbp.number_of_pass_rushers,
    pbp.passer_player_id,
    pbp.receiver_player_id,
    pbp.rusher_player_id,
    pbp.penalty_player_id,
    pbp.posteam,
    pbp.posteam_type,
    pbp.yardline_100,
    pbp.yards_gained,
    pbp.air_yards,
    pbp.yards_after_catch,
    pbp.ep,
    pbp.epa,
    pbp.passing_yards,
    pbp.receiving_yards,
    pbp.rushing_yards,
    pbp.penalty_yards,
    pbp.drive_play_count,
    pbp.drive_time_of_possession,
    pbp.drive_first_downs,
    pbp.drive_yards_penalized
FROM live.silver_pbp pbp;
